version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: mrs-mission-php
    volumes:
      - ./backend:/var/www/
    working_dir: /var/www/

  db: 
    image: mysql:8.0
    container_name: mrs-mission-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rover
      - MYSQL_USER=rover
      - MYSQL_PASSWORD=123456
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: mrs-mission-nginx
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  dbdata:
